// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputFormat } from "./OutputFormat";

export type OutputSettings = { format: OutputFormat, keepAlpha: boolean, destination: string, customDirectory: string | null, keepFolderStructure: boolean, visuallyLossless: boolean, cjpegliDistance: number, forceSubsampling444: boolean, useXyb: boolean, progressive: boolean, stripMetadata: boolean, };
