// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputItem } from "./InputItem";
import type { ProcessingSettings } from "./ProcessingSettings";

export type ProcessingRequest = { items: Array<InputItem>; settings: ProcessingSettings };
