// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcessingError } from "./ProcessingError";

export type ProcessingResult = { successCount: number, skippedCount: number, failedCount: number, errors: Array<ProcessingError>, canceled: boolean, savedBytes: bigint, };
