// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InputItem = {
  id: string;
  sourcePath: string;
  displayName: string;
  relativePath: string;
  sizeBytes: bigint;
  lastModified: bigint;
  isProcessed: boolean | null;
};
