// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputItem } from "./InputItem";

export type ProcessingProgress = {
  completed: number;
  total: number;
  currentItem: InputItem | null;
  currentOutputPath: string | null;
  message: string | null;
  processedItemId: string | null;
  savedBytes: bigint | null;
  activeItemIds: Array<string> | null;
};
