use serde::{Deserialize, Serialize};
use ts_rs::TS;

// Export path for TypeScript types generated by ts-rs
#[cfg(test)]
mod export_tests {
    use super::*;
    use ts_rs::TS;

    #[test]
    fn export_types() {
        let manifest_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        // Target: ../src/bindings (relative to src-tauri)
        let bindings_dir = manifest_dir.parent().unwrap().join("src").join("bindings");

        // Ensure directory exists
        if !bindings_dir.exists() {
            std::fs::create_dir_all(&bindings_dir).expect("Failed to create bindings directory");
        }

        println!("Exporting types to: {:?}", bindings_dir);
        std::env::set_var("TS_RS_EXPORT_DIR", &bindings_dir);

        // Export all types to the bindings directory
        let config = ts_rs::Config::default();
        OutputFormat::export_all(&config).expect("Failed to export OutputFormat");
        AdvancedSettings::export_all(&config).expect("Failed to export AdvancedSettings");
        OutputSettings::export_all(&config).expect("Failed to export OutputSettings");
        WindowSettings::export_all(&config).expect("Failed to export WindowSettings");
        ProcessingSettings::export_all(&config).expect("Failed to export ProcessingSettings");
        AppSettings::export_all(&config).expect("Failed to export AppSettings");
        InputItem::export_all(&config).expect("Failed to export InputItem");
        ProcessingRequest::export_all(&config).expect("Failed to export ProcessingRequest");
        ProcessingProgress::export_all(&config).expect("Failed to export ProcessingProgress");
        ProcessingError::export_all(&config).expect("Failed to export ProcessingError");
        ProcessingResult::export_all(&config).expect("Failed to export ProcessingResult");
        FileStats::export_all(&config).expect("Failed to export FileStats");
        DirEntry::export_all(&config).expect("Failed to export DirEntry");
        PreviewData::export_all(&config).expect("Failed to export PreviewData");
        PreviewMetadata::export_all(&config).expect("Failed to export PreviewMetadata");
        ProcessedStatus::export_all(&config).expect("Failed to export ProcessedStatus");

        // Generate index.ts for easier imports
        let index_content = r#"
// Auto-generated exports
export * from "./OutputFormat";
export * from "./AdvancedSettings";
export * from "./OutputSettings";
export * from "./WindowSettings";
export * from "./ProcessingSettings";
export * from "./AppSettings";
export * from "./InputItem";
export * from "./ProcessingRequest";
export * from "./ProcessingProgress";
export * from "./ProcessingError";
export * from "./ProcessingResult";
export * from "./FileStats";
export * from "./DirEntry";
export * from "./PreviewData";
export * from "./PreviewMetadata";
export * from "./ProcessedStatus";
"#;
        std::fs::write(bindings_dir.join("index.ts"), index_content)
            .expect("Failed to write index.ts");
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "lowercase")]
#[ts(export)]
pub enum OutputFormat {
    Jpeg,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct AdvancedSettings {
    pub concurrency: usize,
    pub preserve_metadata: bool,
    pub preserve_timestamps: bool,
    pub delete_originals: bool,
    pub skip_processed: bool,
    pub play_sound_on_finish: bool,
    pub sound_volume: u8,
    pub clear_input_after_conversion: bool,
    pub warn_before_replace: bool,
    pub recompress_optimized: bool,
    pub size_compare: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct OutputSettings {
    pub format: OutputFormat,
    pub keep_alpha: bool,
    pub destination: String, // "source" or "custom"
    pub custom_directory: Option<String>,
    pub keep_folder_structure: bool,
    pub visually_lossless: bool,
    pub cjpegli_distance: f32,
    pub force_subsampling_444: bool,
    pub use_xyb: bool,
    pub progressive: bool,
    pub strip_metadata: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct WindowSettings {
    pub width: u32,
    pub height: u32,
    pub x: Option<i32>,
    pub y: Option<i32>,
    pub maximized: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ProcessingSettings {
    pub output: OutputSettings,
    pub advanced: AdvancedSettings,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct AppSettings {
    pub output: OutputSettings,
    pub advanced: AdvancedSettings,
    pub window: WindowSettings,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct InputItem {
    pub id: String,
    pub source_path: String,
    pub display_name: String,
    pub relative_path: String,
    pub size_bytes: u64,
    pub last_modified: i64,
    pub is_processed: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ProcessingRequest {
    pub items: Vec<InputItem>,
    pub settings: ProcessingSettings,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ProcessingProgress {
    pub completed: usize,
    pub total: usize,
    pub current_item: Option<InputItem>,
    pub current_output_path: Option<String>,
    pub message: Option<String>,
    pub processed_item_id: Option<String>,
    pub saved_bytes: Option<u64>,
    pub active_item_ids: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ProcessingError {
    pub item: InputItem,
    pub error: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ProcessingResult {
    pub success_count: usize,
    pub skipped_count: usize,
    pub failed_count: usize,
    pub errors: Vec<ProcessingError>,
    pub canceled: bool,
    pub saved_bytes: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct FileStats {
    pub is_file: bool,
    pub is_directory: bool,
    pub size: u64,
    pub mtime: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct DirEntry {
    pub name: String,
    pub is_file: bool,
    pub is_directory: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct PreviewData {
    pub url: String,
    pub metadata: PreviewMetadata,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct PreviewMetadata {
    pub width: Option<u32>,
    pub height: Option<u32>,
    pub format: Option<String>,
    pub size: Option<u64>,
    pub birthtime: Option<i64>,
    #[ts(type = "Record<string, unknown> | null")]
    pub exif: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct ProcessedStatus {
    pub path: String,
    pub is_processed: bool,
}
