// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdvancedSettings = {
  concurrency: number;
  preserveMetadata: boolean;
  preserveTimestamps: boolean;
  deleteOriginals: boolean;
  skipProcessed: boolean;
  playSoundOnFinish: boolean;
  soundVolume: number;
  clearInputAfterConversion: boolean;
  warnBeforeReplace: boolean;
  recompressOptimized: boolean;
  sizeCompare: boolean;
};
