// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreviewMetadata = { width: number | null, height: number | null, format: string | null, size: bigint | null, birthtime: bigint | null, exif: Record<string, unknown> | null, };
