// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvancedSettings } from "./AdvancedSettings";
import type { OutputSettings } from "./OutputSettings";

export type ProcessingSettings = { output: OutputSettings, advanced: AdvancedSettings, };
